language: cpp

os:
  - linux

compiler:
  - gcc

notifications:
 email:
   on_success: change
   on_failure: always

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-4.9 qt4-qmake; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [[ -f /usr/bin/g++ ]]; then sudo rm /usr/bin/g++; fi
  - sudo ln /usr/bin/g++-4.9 /usr/bin/g++

install:
  - "cd $TRAVIS_BUILD_DIR/test"
  - "qmake"

script:
  - "cd $TRAVIS_BUILD_DIR/test"
  - "make"
  - "./test"
